apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ronn4/projectmanager:68ab8e035ec41677c86de8d8c9544c2378188d8c
          ports:
            - containerPort: 8080