apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ronn4/projectmanager-frontend:8dcc1be1a409d59c051913ab26f5655d11c25c9a
          imagePullPolicy: Always
          ports:
            - containerPort: 80