apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ronn4/projectmanager-frontend:ad7a4a3d856bb3bc666baaa2f9b98c211aa8dbaf
          imagePullPolicy: Always
          ports:
            - containerPort: 80