apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ronn4/projectmanager-frontend:6aa87a88b339abb95b7b8b240335585f0cae0648
          imagePullPolicy: Always
          ports:
            - containerPort: 80