backend:
  replicas: 2
  image:
    repository: ronn4/projectmanager
    tag: a9978ef8dbfe43de637ab3e72fc2ab479d8f5b54
    pullPolicy: Always

frontend:
  replicas: 1
  image:
    repository: ronn4/projectmanager-frontend   # ✅ FIXED
    tag: a9978ef8dbfe43de637ab3e72fc2ab479d8f5b54
    pullPolicy: Always

service:
  backend:
    port: 8080
  frontend:
    port: 80

ingress:
  host: ron.project.devops
  tls:
    secretName: tls-secret