backend:
  replicas: 2
  image:
    repository: ronn4/projectmanager
    tag: 82c22af0cb6f3c40ab7b34e68f1684fb8a01b599
    pullPolicy: Always

frontend:
  replicas: 1
  image:
    repository: ronn4/projectmanager-frontend   # ✅ FIXED
    tag: 82c22af0cb6f3c40ab7b34e68f1684fb8a01b599
    pullPolicy: Always

service:
  backend:
    port: 8080
  frontend:
    port: 80

ingress:
  host: ron.project.devops
  tls:
    secretName: tls-secret