backend:
  replicas: 2
  image:
    repository: ronn4/projectmanager
    tag: 35f806dad84e8bb00d53581f6d161f245ca13027
    pullPolicy: Always

frontend:
  replicas: 1
  image:
    repository: ronn4/projectmanager-frontend
    tag: 35f806dad84e8bb00d53581f6d161f245ca13027
    pullPolicy: Always

service:
  backend:
    port: 8080
  frontend:
    port: 80

ingress:
  host: ron.project.devops
  tls:
    secretName: tls-secret