apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: projectmanager
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: frontend

  source:
    repoURL: https://github.com/Ronelleti/projectmanager.git
    targetRevision: vm   # ✅ FIXED (your branch)
    path: projectmanager

    helm:
      valueFiles:
        - values-dev.yaml   # ✅ THIS IS THE KEY FIX

  syncPolicy:
    automated:
      prune: true
      selfHeal: true