apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ronn4/projectmanager-frontend:2d80d2c506b0c9ede2f67d39e5c3094ac964d5a0
          imagePullPolicy: Always
          ports:
            - containerPort: 80