apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ronn4/projectmanager-frontend:47b8997bc67adc267c1c3f1cdb2ab9b3aa13ba23
          imagePullPolicy: Always
          ports:
            - containerPort: 80