apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
spec:
  schedule: "0 2 * * *"   # ✅ every day at 02:00

  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1

  jobTemplate:
    spec:
      backoffLimit: 2

      template:
        spec:
          containers:
            - name: backup
              image: postgres:15

              env:
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: POSTGRES_USER

                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: POSTGRES_PASSWORD

                - name: DB_NAME
                  value: {{ .Values.database.name }}

              command:
                - /bin/sh
                - -c
                - |
                  mkdir -p /backup

                  echo "Starting backup..."

                  FILE="/backup/backup-$(date +%Y%m%d%H%M).sql"

                  pg_dump -h postgres -U $POSTGRES_USER $DB_NAME > $FILE

                  if [ $? -eq 0 ]; then
                    echo "Backup successful → cleaning old backups"

                    # 🔥 keep ONLY latest file
                    ls -t /backup/*.sql | tail -n +2 | xargs -r rm --

                  else
                    echo "Backup failed → NOT deleting old backups"
                  fi

                  echo "Done"

              volumeMounts:
                - name: backup-storage
                  mountPath: /backup

          restartPolicy: OnFailure

          volumes:
            - name: backup-storage
              emptyDir: {}