apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
spec:
  encryptedData:
    POSTGRES_DB: AgCX6aoAhwPJ2icY77FKkA8t645HakgV/ojeDN4ZadS2gW9VGhoYb4LpEYCaFlOpAPWD65uxHtWTUvCFYL6NuMGyO17NDbId6m2BKKonKA1sXhLZs9v13LlgidyFeoMLGcPji11R2+X3w6JdDvv7NH8T77mr11qcz+5X2+sHlXeWiD0pRxdkdj8ZliKqvicbYr3nefVMKkfbeTEfNBBrKGsHPuLaaxDrJfDv0QZJzWe2hDgeMkio7/+Ar3PI>
    POSTGRES_PASSWORD: AgCFlHwjqauAoNOmcuMUYM9qqOC9SOM+Ha14+o3wpG0tjYz6xgfYqnnZeHkyFg7DA5UkvCk+re+w/LMA2PCtoWrZUYGm/bCjaXsHqv0UnJUe1QrnWKF375zibPIlEYsOXjI2He+czkhTPZn+hXinwBqt11j0L3EygNKdc0P54Mnzt64wAeLjvHmUg3qUe64jmdiseRFNyErJaOjYOJoLR36dGMYyk3+GzNUH/MusrGnEcMNk2y3nGi>
    POSTGRES_USER: AgATdL1X4uoZTL7affhxmbI7i2y1komOKYnWBRC9nmtUCJ1PH6+QPFrqtC4hYHKNAV+nYVJXkCTzphEyaAovDa+95QLeHdnuJgdrCi7ai+K8el6LWafWg2KZZ2eiQo8zfkkvRhTdhNse3EuxkSOAPL8cSD8GV8RH3bvqIn1/rhEiOu352zyG+eLYYfiEZZwBHs9FlGgLbnMyzHXtq6OK59mJDyo0mGylVdQlExUBdjE7I5dxU2QdwlKvNX>
  template:
    metadata:
      name: postgres-secret